import React from 'react';
import { enginePrintCss, engineScreenCss } from './printStyles';

/**
 * Root wrapper for all v2 print templates.
 * Provides base typography, copy badge, print footer, and engine marker.
 */
export default function InvoicePrintRoot({ templateId, data, children, showFooter = true }) {
  if (!data) return null;

  return (
    <div
      className={`invoice-print-engine invoice-template invoice-engine-${templateId}`}
      data-print-engine="v2"
      data-template={templateId}
    >
      {data.copyLabel && data.copyLabel !== 'ORIGINAL' ? (
        <div className="ipe-copy-badge">{data.copyLabel}</div>
      ) : null}

      {children}

      {showFooter ? (
        <div className="ipe-print-footer no-print-screen-hidden">
          <span>Generated by ERP · {data.company?.name || 'Billing Software'}</span>
          <span>Printed: {data.printMeta?.timestamp || ''}</span>
        </div>
      ) : null}

      <style>{engineScreenCss}</style>
      <style>{enginePrintCss}</style>
    </div>
  );
}
