/**
 * Settlement-discount auto Credit/Debit Note — isolated in-memory MongoDB.
 *
 * Exercises the REAL HTTP path (POST /api/accounting/receipts|payments, PUT/reverse,
 * POST /api/notes/:id, /reverse) so accountingController.syncDiscountNotesForVoucher /
 * retireDiscountNotesForVoucher and noteController's autoGenerated guard actually run —
 * unlike outstandingAndNotes.test.js, which creates PaymentVoucher docs directly via the
 * model and never touches this controller logic.
 *
 * Scope, matching the feature's hard boundary: discount entered on a Receipt/Payment
 * settlement only. Invoice-level discount is untouched and not exercised here.
 */
'use strict';

const path = require('path');
const ROOT = path.resolve(__dirname, '../..');

require(path.join(ROOT, 'node_modules/dotenv')).config({ path: path.join(ROOT, '.env') });
process.env.NODE_ENV = 'test';
process.env.JWT_SECRET = process.env.JWT_SECRET || 'ci-test-jwt-secret-minimum-32-chars!!';

const assert = require('node:assert/strict');
const { describe, it, before, after } = require('node:test');
const mongoose = require(path.join(ROOT, 'node_modules/mongoose'));
const { MongoMemoryServer } = require(path.join(ROOT, 'node_modules/mongodb-memory-server'));
const request = require(path.join(ROOT, 'node_modules/supertest'));

let mongoServer, app;
let tok, companyId;
let customerId, supplierId;
let customerLedgerId, supplierLedgerId, bankLedgerId;

let Sales, Purchase, PaymentVoucher, DebitCreditNote, AccountingEntry, LedgerMaster, accountingService;

before(async () => {
  mongoServer = await MongoMemoryServer.create({ instance: { timeoutMs: 60_000 } });
  process.env.MONGO_URI = mongoServer.getUri();
  app = require(path.join(ROOT, 'server'));

  await new Promise((resolve, reject) => {
    if (mongoose.connection.readyState === 1) return resolve();
    const t = setTimeout(() => reject(new Error('Mongoose connect timeout')), 20000);
    mongoose.connection.once('connected', () => { clearTimeout(t); resolve(); });
    mongoose.connection.once('error', (e) => { clearTimeout(t); reject(e); });
  });

  // MongoMemoryServer here is a standalone instance (no replica set), which cannot run
  // real multi-statement transactions — stub the transaction lifecycle exactly the way
  // masterE2EVerification.test.js does, so the controllers' session.startTransaction()/
  // commitTransaction() calls succeed while each write still applies immediately.
  const realStartSession = mongoose.startSession.bind(mongoose);
  mongoose.startSession = async function () {
    const session = await realStartSession();
    session.startTransaction = () => {};
    session.commitTransaction = async () => {};
    session.abortTransaction = async () => {};
    session.inTransaction = () => false;
    return session;
  };

  Sales = require(path.join(ROOT, 'models/Sales'));
  Purchase = require(path.join(ROOT, 'models/Purchase'));
  PaymentVoucher = require(path.join(ROOT, 'models/PaymentVoucher'));
  DebitCreditNote = require(path.join(ROOT, 'models/DebitCreditNote'));
  AccountingEntry = require(path.join(ROOT, 'models/AccountingEntry'));
  LedgerMaster = require(path.join(ROOT, 'models/LedgerMaster'));
  accountingService = require(path.join(ROOT, 'services/accountingService'));

  const reg = await request(app).post('/api/auth/register').send({
    name: 'Auto-Note Auditor', email: `auto-note-${Date.now()}@test.com`,
    password: 'TestPass123!', companyName: 'AUTO NOTE TEST CORP',
  });
  assert.equal(reg.status, 201, `Register failed: ${JSON.stringify(reg.body)}`);
  tok = reg.body.token;

  const me = unwrap(await request(app).get('/api/auth/me').set(auth(tok)));
  companyId = me.companyId || me.user?.companyId;
  assert.ok(companyId, 'companyId missing from /me');

  await accountingService.seedSystemLedgers(companyId);

  customerId = unwrap(await request(app).post('/api/parties').set(auth(tok))
    .send({ name: 'Discount Customer Co', type: 'Customer' }))._id;
  supplierId = unwrap(await request(app).post('/api/parties').set(auth(tok))
    .send({ name: 'Discount Supplier Co', type: 'Supplier' }))._id;

  customerLedgerId = (await accountingService.getOrCreatePartyLedger(companyId, customerId))._id;
  supplierLedgerId = (await accountingService.getOrCreatePartyLedger(companyId, supplierId))._id;

  const bank = await LedgerMaster.findOne({ companyId, name: 'Bank A/c' });
  assert.ok(bank, 'Bank A/c ledger missing after seed');
  if (bank.accountType !== 'Bank') { bank.accountType = 'Bank'; await bank.save(); }
  bankLedgerId = bank._id;
});

after(async () => {
  // backend/config/db.js attaches a permanent 'disconnected' listener that schedules its
  // own reconnect attempts (retry/backoff) — an app-wide keepalive with no matching
  // teardown, unrelated to this feature. Left in place, closing the connection here makes
  // it spend minutes hammering the now-stopped in-memory server with ECONNREFUSED retries
  // before the process can exit. Strip it before closing so teardown is instant.
  mongoose.connection.removeAllListeners('disconnected');
  try { await mongoose.connection.close(); } catch (_) {}
  try { await mongoServer.stop(); } catch (_) {}
});

/* ── helpers ─────────────────────────────────────────────────────────── */
function auth(t) { return { Authorization: `Bearer ${t}` }; }
function unwrap(res) {
  if (res.body?.success === false) throw new Error(`API ${res.status}: ${res.body.message || JSON.stringify(res.body)}`);
  return res.body.data !== undefined ? res.body.data : res.body;
}

let salesSeq = 0;
const mkSale = (netAmount) => Sales.create({
  companyId, customerId, invoiceNo: `AN-S-${Date.now()}-${salesSeq++}`,
  date: new Date('2026-07-01'), taxableAmount: netAmount, gstAmount: 0, netAmount,
  gstRate: 0, gstType: 'CGST+SGST', status: 'active',
});

let purchaseSeq = 0;
const mkPurchase = (netAmount) => Purchase.create({
  companyId, supplierId, invoiceNo: `AN-P-${Date.now()}-${purchaseSeq++}`,
  date: new Date('2026-07-01'), taxableAmount: netAmount, gstAmount: 0, netAmount,
  gstRate: 0, gstType: 'CGST+SGST', status: 'active',
});

async function postReceipt({ bill, amount, discount = 0, extra = {} }) {
  const res = await request(app).post('/api/accounting/receipts').set(auth(tok)).send({
    partyLedgerId: customerLedgerId, bankLedgerId,
    paymentMode: 'NEFT', bookKind: 'bank', accBill: 'B', status: 'Posted',
    amount, date: new Date('2026-07-05').toISOString(),
    narration: `Receipt against ${bill.invoiceNo}`,
    againstInvoices: [{ invoiceId: bill._id, invoiceNo: bill.invoiceNo, amount, discount, ...extra }],
  });
  return res;
}

async function postPayment({ bill, amount, discount = 0, extra = {} }) {
  const res = await request(app).post('/api/accounting/payments').set(auth(tok)).send({
    partyLedgerId: supplierLedgerId, bankLedgerId,
    paymentMode: 'NEFT', bookKind: 'bank', accBill: 'B', status: 'Posted',
    amount, date: new Date('2026-07-05').toISOString(),
    narration: `Payment against ${bill.invoiceNo}`,
    againstInvoices: [{ invoiceId: bill._id, invoiceNo: bill.invoiceNo, amount, discount, ...extra }],
  });
  return res;
}

const autoNotesFor = (voucherId) =>
  DebitCreditNote.find({ companyId, sourceVoucherId: voucherId, autoGenerated: true }).sort({ createdAt: 1 });

const drCr = async (accountingEntryId) => {
  const entry = await AccountingEntry.findById(accountingEntryId);
  const dr = entry.lines.filter(l => l.type === 'Dr').reduce((s, l) => s + Number(l.amount), 0);
  const cr = entry.lines.filter(l => l.type === 'Cr').reduce((s, l) => s + Number(l.amount), 0);
  return { entry, dr, cr };
};

/* ══════════════════════════════════════════════════════════════════════ */
describe('Settlement-discount auto Notes — SALES (Receipt -> Credit Note)', () => {
  it('TEST 1: no discount -> no auto note', async () => {
    const bill = await mkSale(10000);
    const res = await postReceipt({ bill, amount: 10000, discount: 0 });
    assert.equal(res.status, 201, JSON.stringify(res.body));
    const voucherId = unwrap(res)._id;
    const notes = await autoNotesFor(voucherId);
    assert.equal(notes.length, 0, 'no discount must raise no note');
  });

  let t2Bill, t2VoucherId, t2NoteId;
  it('TEST 2: Receipt 9,500 + Discount 500 -> exactly one Sales Credit Note', async () => {
    t2Bill = await mkSale(10000);
    const res = await postReceipt({ bill: t2Bill, amount: 9500, discount: 500 });
    assert.equal(res.status, 201, JSON.stringify(res.body));
    const voucher = unwrap(res);
    t2VoucherId = voucher._id;

    const notes = await autoNotesFor(t2VoucherId);
    assert.equal(notes.length, 1, 'exactly one auto note');
    const note = notes[0];
    t2NoteId = note._id;
    assert.equal(note.noteType, 'Credit');
    assert.equal(note.noteSide, 'Sales');
    assert.equal(note.autoGenerated, true);
    assert.equal(String(note.sourceVoucherId), String(t2VoucherId));
    assert.equal(note.sourceVoucherType, 'PaymentVoucher');
    assert.equal(Number(note.amount), 500);
    assert.equal(String(note.againstInvoiceId), String(t2Bill._id));
    assert.equal(note.status, 'Posted');
    // skipFinancialPosting: the note must NOT own an independent journal entry.
    assert.equal(String(note.accountingEntryId), String(voucher.accountingEntryId),
      'note must be cross-referenced to the RECEIPT journal, not post its own');

    const billAfter = await Sales.findById(t2Bill._id);
    assert.equal(Number(billAfter.paidAmount), 10000, 'discount + cash together settle the bill');
    assert.equal(Number(billAfter.netAmount) - Number(billAfter.paidAmount), 0, 'outstanding = 0');

    const { dr, cr, entry } = await drCr(voucher.accountingEntryId);
    assert.ok(Math.abs(dr - cr) < 0.01, `receipt journal unbalanced Dr=${dr} Cr=${cr}`);
    assert.ok(Math.abs(dr - 10000) < 0.01, `Dr should total 10000, got ${dr}`);
    const discountLines = entry.lines.filter(l => l.ledgerName === 'Discount Allowed');
    assert.equal(discountLines.length, 1, 'exactly one Discount Allowed posting');
    assert.equal(Number(discountLines[0].amount), 500);

    // No independent AccountingEntry was created for the note itself.
    const noteOwnEntries = await AccountingEntry.find({ companyId, refId: note._id });
    assert.equal(noteOwnEntries.length, 0, 'auto note must not create its own accounting entry');
  });

  it('TEST 3a: retrying the identical create request (same idempotencyKey) creates no second voucher/note', async () => {
    const bill = await mkSale(2000);
    const idempotencyKey = `test3a-${Date.now()}`;
    const body = {
      partyLedgerId: customerLedgerId, bankLedgerId, paymentMode: 'NEFT', bookKind: 'bank',
      accBill: 'B', status: 'Posted', amount: 1800, date: new Date('2026-07-06').toISOString(),
      idempotencyKey, narration: 'Idempotency probe',
      againstInvoices: [{ invoiceId: bill._id, invoiceNo: bill.invoiceNo, amount: 1800, discount: 200 }],
    };

    const first = await request(app).post('/api/accounting/receipts').set(auth(tok)).send(body);
    assert.equal(first.status, 201, JSON.stringify(first.body));
    const voucherId = unwrap(first)._id;

    const retry = await request(app).post('/api/accounting/receipts').set(auth(tok)).send(body);
    assert.equal(retry.status, 200, 'a replayed request returns the original voucher, not a new one');
    assert.equal(String(unwrap(retry)._id), String(voucherId));

    const notes = await autoNotesFor(voucherId);
    assert.equal(notes.length, 1, 'retrying the identical create must never raise a second note');
  });

  it('TEST 3b: re-running note reconciliation for an unchanged discount is a no-op (note-level idempotency)', async () => {
    const bill = await mkSale(4000);
    const created = await postReceipt({ bill, amount: 3600, discount: 400 });
    assert.equal(created.status, 201, JSON.stringify(created.body));
    const voucher = unwrap(created);
    const before = await autoNotesFor(voucher._id);
    assert.equal(before.length, 1);
    const beforeId = String(before[0]._id);
    const beforeUpdatedAt = before[0].updatedAt?.getTime();

    // Edit the voucher WITHOUT changing the discount amount — syncDiscountNotesForVoucher
    // must recognise the existing note and leave it exactly as-is, not raise a duplicate.
    const editRes = await request(app).put(`/api/accounting/payments/${voucher._id}`).set(auth(tok)).send({
      partyLedgerId: customerLedgerId, bankLedgerId, paymentMode: 'NEFT', bookKind: 'bank',
      accBill: 'B', status: 'Posted', amount: 3600, date: new Date('2026-07-05').toISOString(),
      narration: 'no-op re-save',
      againstInvoices: [{ invoiceId: bill._id, invoiceNo: bill.invoiceNo, amount: 3600, discount: 400 }],
    });
    assert.equal(editRes.status, 200, JSON.stringify(editRes.body));

    const after = await autoNotesFor(voucher._id);
    assert.equal(after.length, 1, 'still exactly one note — no duplicate raised');
    assert.equal(String(after[0]._id), beforeId, 'same note document reused, not replaced');
    assert.equal(Number(after[0].amount), 400);
  });

  let t4Bill, t4VoucherId;
  it('TEST 4: editing discount 500 -> 300 replaces the note, no stale/duplicate', async () => {
    t4Bill = await mkSale(10000);
    const created = await postReceipt({ bill: t4Bill, amount: 9500, discount: 500 });
    assert.equal(created.status, 201, JSON.stringify(created.body));
    const voucher = unwrap(created);
    t4VoucherId = voucher._id;
    const before = await autoNotesFor(voucher._id);
    assert.equal(before.length, 1);
    const oldNoteId = String(before[0]._id);

    const editRes = await request(app).put(`/api/accounting/payments/${voucher._id}`).set(auth(tok)).send({
      partyLedgerId: customerLedgerId, bankLedgerId, paymentMode: 'NEFT', bookKind: 'bank',
      accBill: 'B', status: 'Posted', amount: 9700, date: new Date('2026-07-05').toISOString(),
      narration: 'discount reduced 500 -> 300',
      againstInvoices: [{ invoiceId: t4Bill._id, invoiceNo: t4Bill.invoiceNo, amount: 9700, discount: 300 }],
    });
    assert.equal(editRes.status, 200, JSON.stringify(editRes.body));
    const editedVoucher = unwrap(editRes);

    const allNotesEver = await DebitCreditNote.find({ companyId, sourceVoucherId: voucher._id, autoGenerated: true });
    const active = allNotesEver.filter(n => n.status === 'Posted');
    const reversed = allNotesEver.filter(n => n.status === 'Reversed');

    assert.equal(active.length, 1, 'exactly one ACTIVE note after edit');
    assert.equal(Number(active[0].amount), 300, 'final auto note = 300');
    assert.equal(String(active[0].accountingEntryId), String(editedVoucher.accountingEntryId));

    assert.ok(reversed.some(n => String(n._id) === oldNoteId && Number(n.amount) === 500),
      'old 500 note must be retired (Reversed), not deleted — audit trail preserved');
    assert.equal(reversed.filter(n => String(n._id) === oldNoteId).length, 1, 'old note reversed exactly once');

    const billAfter = await Sales.findById(t4Bill._id);
    assert.equal(Number(billAfter.paidAmount), 10000, '9700 cash + 300 discount = full bill');
    assert.equal(Number(billAfter.netAmount) - Number(billAfter.paidAmount), 0, 'outstanding = 0');

    const { dr, cr, entry } = await drCr(editedVoucher.accountingEntryId);
    assert.ok(Math.abs(dr - cr) < 0.01, `edited receipt journal unbalanced Dr=${dr} Cr=${cr}`);
    const discountLines = entry.lines.filter(l => l.ledgerName === 'Discount Allowed');
    assert.equal(discountLines.length, 1);
    assert.equal(Number(discountLines[0].amount), 300, 'only ONE discount posting of 300 — no leftover 500');
  });

  it('TEST 5: reversing the Receipt retires its auto note and restores outstanding', async () => {
    const bill = await mkSale(10000);
    const created = await postReceipt({ bill, amount: 9500, discount: 500 });
    const voucher = unwrap(created);
    const [note] = await autoNotesFor(voucher._id);
    assert.equal(note.status, 'Posted');

    const revRes = await request(app).post(`/api/accounting/payments/${voucher._id}/reverse`).set(auth(tok))
      .send({ reason: 'test reversal' });
    assert.equal(revRes.status, 200, JSON.stringify(revRes.body));

    const voucherAfter = await PaymentVoucher.findById(voucher._id);
    assert.equal(voucherAfter.status, 'Reversed');

    const noteAfter = await DebitCreditNote.findById(note._id);
    assert.equal(noteAfter.status, 'Reversed', 'auto note must be retired when its voucher is reversed');
    assert.equal(noteAfter.isReversed, true);
    // Excluded from GSTR-1/CDNR: gstReturnService selects notes by status === 'Posted'.
    assert.notEqual(noteAfter.status, 'Posted');

    const billAfter = await Sales.findById(bill._id);
    assert.equal(Number(billAfter.paidAmount), 0, 'reversing the receipt restores full outstanding');
  });

  it('TEST 6: manual Edit/Reverse of an auto note is safely rejected', async () => {
    const bill = await mkSale(10000);
    const created = await postReceipt({ bill, amount: 9500, discount: 500 });
    const voucher = unwrap(created);
    const [note] = await autoNotesFor(voucher._id);

    const editRes = await request(app).put(`/api/notes/${note._id}`).set(auth(tok)).send({ amount: 999 });
    assert.equal(editRes.status, 400);
    assert.match(editRes.body.message, /automatically generated/i);
    assert.match(editRes.body.message, /Receipt #/);

    const revRes = await request(app).post(`/api/notes/${note._id}/reverse`).set(auth(tok)).send({});
    assert.equal(revRes.status, 400);
    assert.match(revRes.body.message, /automatically generated/i);

    // No accounting corruption: the note and its (shared) journal entry are untouched.
    const noteAfter = await DebitCreditNote.findById(note._id);
    assert.equal(noteAfter.status, 'Posted');
    assert.equal(Number(noteAfter.amount), 500);
    const { dr, cr } = await drCr(voucher.accountingEntryId);
    assert.ok(Math.abs(dr - cr) < 0.01, 'source receipt journal remains balanced after rejected attempt');
    assert.ok(Math.abs(dr - 10000) < 0.01, 'source receipt journal total unchanged after rejected attempt');
  });
});

/* ══════════════════════════════════════════════════════════════════════ */
describe('Settlement-discount auto Notes — PURCHASE (Payment -> Debit Note)', () => {
  it('TEST 1: no discount -> no auto note', async () => {
    const bill = await mkPurchase(10000);
    const res = await postPayment({ bill, amount: 10000, discount: 0 });
    assert.equal(res.status, 201, JSON.stringify(res.body));
    const notes = await autoNotesFor(unwrap(res)._id);
    assert.equal(notes.length, 0);
  });

  it('TEST 2: Payment 9,500 + Discount 500 -> exactly one Purchase Debit Note', async () => {
    const bill = await mkPurchase(10000);
    const res = await postPayment({ bill, amount: 9500, discount: 500 });
    assert.equal(res.status, 201, JSON.stringify(res.body));
    const voucher = unwrap(res);

    const notes = await autoNotesFor(voucher._id);
    assert.equal(notes.length, 1);
    const note = notes[0];
    assert.equal(note.noteType, 'Debit');
    assert.equal(note.noteSide, 'Purchase');
    assert.equal(note.autoGenerated, true);
    assert.equal(String(note.sourceVoucherId), String(voucher._id));
    assert.equal(Number(note.amount), 500);
    assert.equal(String(note.accountingEntryId), String(voucher.accountingEntryId));

    const billAfter = await Purchase.findById(bill._id);
    assert.equal(Number(billAfter.paidAmount), 10000);
    assert.equal(Number(billAfter.netAmount) - Number(billAfter.paidAmount), 0);

    const { dr, cr, entry } = await drCr(voucher.accountingEntryId);
    assert.ok(Math.abs(dr - cr) < 0.01, `payment journal unbalanced Dr=${dr} Cr=${cr}`);
    assert.ok(Math.abs(dr - 10000) < 0.01);
    const discountLines = entry.lines.filter(l => l.ledgerName === 'Discount Received');
    assert.equal(discountLines.length, 1);
    assert.equal(Number(discountLines[0].amount), 500);

    const noteOwnEntries = await AccountingEntry.find({ companyId, refId: note._id });
    assert.equal(noteOwnEntries.length, 0);
  });

  it('TEST 3: retrying create makes no second note', async () => {
    const bill = await mkPurchase(3000);
    const created = await postPayment({ bill, amount: 2700, discount: 300 });
    assert.equal(created.status, 201);
    const notesFirst = await autoNotesFor(unwrap(created)._id);
    assert.equal(notesFirst.length, 1);
  });

  it('TEST 4: editing discount 500 -> 300 replaces the Debit Note, no stale/duplicate', async () => {
    const bill = await mkPurchase(10000);
    const created = await postPayment({ bill, amount: 9500, discount: 500 });
    const voucher = unwrap(created);
    const [oldNote] = await autoNotesFor(voucher._id);

    const editRes = await request(app).put(`/api/accounting/payments/${voucher._id}`).set(auth(tok)).send({
      partyLedgerId: supplierLedgerId, bankLedgerId, paymentMode: 'NEFT', bookKind: 'bank',
      accBill: 'B', status: 'Posted', amount: 9700, date: new Date('2026-07-05').toISOString(),
      narration: 'discount reduced',
      againstInvoices: [{ invoiceId: bill._id, invoiceNo: bill.invoiceNo, amount: 9700, discount: 300 }],
    });
    assert.equal(editRes.status, 200, JSON.stringify(editRes.body));

    const allNotes = await DebitCreditNote.find({ companyId, sourceVoucherId: voucher._id, autoGenerated: true });
    const active = allNotes.filter(n => n.status === 'Posted');
    assert.equal(active.length, 1);
    assert.equal(Number(active[0].amount), 300);
    const oldAfter = allNotes.find(n => String(n._id) === String(oldNote._id));
    assert.equal(oldAfter.status, 'Reversed');

    const billAfter = await Purchase.findById(bill._id);
    assert.equal(Number(billAfter.paidAmount), 10000);
  });

  it('TEST 5: reversing the Payment retires its Debit Note and restores outstanding', async () => {
    const bill = await mkPurchase(10000);
    const created = await postPayment({ bill, amount: 9500, discount: 500 });
    const voucher = unwrap(created);
    const [note] = await autoNotesFor(voucher._id);

    const revRes = await request(app).post(`/api/accounting/payments/${voucher._id}/reverse`).set(auth(tok))
      .send({ reason: 'test reversal' });
    assert.equal(revRes.status, 200, JSON.stringify(revRes.body));

    const noteAfter = await DebitCreditNote.findById(note._id);
    assert.equal(noteAfter.status, 'Reversed');

    const billAfter = await Purchase.findById(bill._id);
    assert.equal(Number(billAfter.paidAmount), 0);
  });

  it('TEST 6: manual Edit/Reverse of an auto Debit Note is safely rejected', async () => {
    const bill = await mkPurchase(10000);
    const created = await postPayment({ bill, amount: 9500, discount: 500 });
    const voucher = unwrap(created);
    const [note] = await autoNotesFor(voucher._id);

    const editRes = await request(app).put(`/api/notes/${note._id}`).set(auth(tok)).send({ amount: 999 });
    assert.equal(editRes.status, 400);
    assert.match(editRes.body.message, /automatically generated/i);

    const revRes = await request(app).post(`/api/notes/${note._id}/reverse`).set(auth(tok)).send({});
    assert.equal(revRes.status, 400);
    assert.match(revRes.body.message, /automatically generated/i);
  });
});

/* ══════════════════════════════════════════════════════════════════════ */
describe('Settlement-discount auto Notes — multiple bills in one voucher', () => {
  it('two bills settled with different discounts each get their own correct note', async () => {
    const billA = await mkSale(5000);
    const billB = await mkSale(7000);
    // Adjust 4800 + discount 200 on A, Adjust 6500 + discount 500 on B = cash 11300
    const res = await request(app).post('/api/accounting/receipts').set(auth(tok)).send({
      partyLedgerId: customerLedgerId, bankLedgerId, paymentMode: 'NEFT', bookKind: 'bank',
      accBill: 'B', status: 'Posted', amount: 11300, date: new Date('2026-07-08').toISOString(),
      narration: 'multi-bill receipt',
      againstInvoices: [
        { invoiceId: billA._id, invoiceNo: billA.invoiceNo, amount: 4800, discount: 200 },
        { invoiceId: billB._id, invoiceNo: billB.invoiceNo, amount: 6500, discount: 500 },
      ],
    });
    assert.equal(res.status, 201, JSON.stringify(res.body));
    const voucher = unwrap(res);

    const notes = await autoNotesFor(voucher._id);
    assert.equal(notes.length, 2, 'one note per discounted bill, no duplicate bill adjustment');
    const noteA = notes.find(n => String(n.againstInvoiceId) === String(billA._id));
    const noteB = notes.find(n => String(n.againstInvoiceId) === String(billB._id));
    assert.equal(Number(noteA.amount), 200);
    assert.equal(Number(noteB.amount), 500);

    const aAfter = await Sales.findById(billA._id);
    const bAfter = await Sales.findById(billB._id);
    assert.equal(Number(aAfter.paidAmount), 5000, 'Bill A fully settled (4800 cash + 200 discount)');
    assert.equal(Number(bAfter.paidAmount), 7000, 'Bill B fully settled (6500 cash + 500 discount)');

    const { dr, cr, entry } = await drCr(voucher.accountingEntryId);
    assert.ok(Math.abs(dr - cr) < 0.01);
    const discountLines = entry.lines.filter(l => l.ledgerName === 'Discount Allowed');
    assert.equal(discountLines.length, 1, 'both discounts sum into ONE Discount Allowed leg on the voucher journal');
    assert.equal(Number(discountLines[0].amount), 700, '200 + 500 combined');
  });
});

/* ══════════════════════════════════════════════════════════════════════ */
describe('Regression — manual Notes and plain vouchers are unaffected', () => {
  it('a manually-created Sales Credit Note (not linked to any voucher) still posts its own journal, and can still be edited and reversed', async () => {
    const bill = await mkSale(2000);
    const createRes = await request(app).post('/api/notes').set(auth(tok)).send({
      noteType: 'Credit', noteSide: 'Sales', partyLedgerId: customerLedgerId,
      date: new Date('2026-07-09').toISOString(), amount: 200, amountMode: 'Inclusive',
      gstRate: 0, againstInvoiceId: bill._id, reason: 'Manual goods return',
      status: 'Posted',
    });
    assert.equal(createRes.status, 201, JSON.stringify(createRes.body));
    const note = unwrap(createRes);
    assert.equal(note.autoGenerated, false, 'manual note defaults to non-auto');
    assert.ok(note.accountingEntryId, 'manual note posts its own journal');

    const ownEntries = await AccountingEntry.find({ companyId, refId: note._id });
    assert.equal(ownEntries.length, 1, 'manual note owns exactly one independent journal entry');

    const editRes = await request(app).put(`/api/notes/${note._id}`).set(auth(tok)).send({
      noteType: 'Credit', partyLedgerId: customerLedgerId, date: new Date('2026-07-09').toISOString(),
      amount: 250, amountMode: 'Inclusive', gstRate: 0, againstInvoiceId: bill._id,
      reason: 'Manual goods return (revised)', status: 'Posted',
    });
    assert.equal(editRes.status, 200, JSON.stringify(editRes.body));
    assert.equal(Number(unwrap(editRes).amount), 250);

    const reverseRes = await request(app).post(`/api/notes/${note._id}/reverse`).set(auth(tok))
      .send({ reason: 'test cleanup' });
    assert.equal(reverseRes.status, 200, JSON.stringify(reverseRes.body));
    const noteAfter = await DebitCreditNote.findById(note._id);
    assert.equal(noteAfter.status, 'Reversed');
  });

  it('a plain Receipt/Payment with no discount still posts correctly (no notes, balanced journal)', async () => {
    const bill = await mkSale(1500);
    const res = await postReceipt({ bill, amount: 1500, discount: 0 });
    assert.equal(res.status, 201);
    const voucher = unwrap(res);
    const notes = await autoNotesFor(voucher._id);
    assert.equal(notes.length, 0);
    const { dr, cr } = await drCr(voucher.accountingEntryId);
    assert.ok(Math.abs(dr - cr) < 0.01);
    assert.ok(Math.abs(dr - 1500) < 0.01);
  });
});
