/**
 * Domain / HTTP error codes — keep stable for frontend Sprint 1.3 mapping.
 */
module.exports = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_INVALID: 'AUTH_INVALID',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  COMPANY_REQUIRED: 'COMPANY_REQUIRED',
  SUBSCRIPTION_INACTIVE: 'SUBSCRIPTION_INACTIVE',
  LICENSE_INVALID: 'LICENSE_INVALID',
  FEATURE_LOCKED: 'FEATURE_LOCKED',
  PERIOD_LOCKED: 'PERIOD_LOCKED',
  TRANSACTION_FAILED: 'TRANSACTION_FAILED',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL: 'INTERNAL_ERROR',
};
